"""column unsafe_password removed

Revision ID: 124feea18974
Revises: d01dfdfa09e5
Create Date: 2022-02-22 09:11:09.307651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '124feea18974'
down_revision = 'd01dfdfa09e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'unsafe_password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('unsafe_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
