"""criando coluna source integer

Revision ID: 36251c50aa4f
Revises: 3b4ee44e01f5
Create Date: 2022-02-09 09:14:57.654484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36251c50aa4f'
down_revision = '3b4ee44e01f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_records', sa.Column('source', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_records', 'source')
    # ### end Alembic commands ###
