"""deletando coluna source

Revision ID: 3b4ee44e01f5
Revises: 8df557310160
Create Date: 2022-02-09 09:12:33.993646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b4ee44e01f5'
down_revision = '8df557310160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('call_records', 'source')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call_records', sa.Column('source', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
