"""criacao da tabela call_records

Revision ID: 8df557310160
Revises: 
Create Date: 2022-02-08 09:38:06.575498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8df557310160"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "call_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(10), nullable=False),
        sa.Column("destination", sa.String(), nullable=False),
        sa.Column("start_time", sa.Date(), nullable=True),
        sa.Column("end_time", sa.Date(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("call_records")
    # ### end Alembic commands ###
